# .travis.yml - configuration file for the travis continuous integration service
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

# PHP versions to test against.
# See: http://docs.travis-ci.com/user/languages/php/
php:
  - 5.6
  - 7.1
  - 7.2

before_install:
  - mkdir -v tests
install:
  - curl -so tests/composer.phar https://getcomposer.org/composer.phar
  - php tests/composer.phar -d=tests require drush/drush
script:
  - ant -f base.xml composer-check
after_script:
  - ant -f base.xml composer-show
